#!/bin/sh
# setup/remove git filter and diff text converter

usage() {
    s="$(basename "$0")"
    printf "%s" "\
$s
    handles git configs to transparently use sec in your repo

    on  - install sec in your git repo
    off  - removes sec from your git repo
"
}

cmd="$1"
[ -n "$cmd" ] && shift

is_git_mode_on() {
    git config --local filter.sec.clean >/dev/null 2>&1
}
turn_git_mode_off() {
    git config --local --unset-all filter.sec.clean
    git config --local --unset-all filter.sec.smudge
    git config --local --unset-all filter.sec.required
    git config --local --unset-all diff.sec.textconv

    git_root_dir=$(git rev-parse --show-toplevel)
    gitattr_file="$git_root_dir/.gitattributes"
    tmpfile_git_off_patterns="$(mktemp)"
    [ -f "$gitattr_file" ] || return 0
    paths="$(sec l | grep -v '^#' | grep -v '^age' | grep -v '^$')"
    printf "%s" "$paths" | while IFS= read -r c; do line="$c  filter=sec diff=sec"
            echo "$line" >> "$tmpfile_git_off_patterns"; done
    new_gitattr_content="$(grep -v -F -f "$tmpfile_git_off_patterns" "$gitattr_file")"
    [ -z "$new_gitattr_content" ] && rm -f "$gitattr_file" && return 0
    printf "%s" "$new_gitattr_content" > "$gitattr_file"
}
turn_git_mode_on() {
    git config --local filter.sec.clean "sec-git clean %f"
    git config --local filter.sec.smudge "sec-git smudge %f"
    git config --local filter.sec.required true
    git config --local diff.sec.textconv "sec-git diff"

    git_root_dir=$(git rev-parse --show-toplevel)
    gitattr_file="$git_root_dir/.gitattributes"
    paths="$(sec l | grep -v '^#' | grep -v '^age' | grep -v '^$')"
    printf "%s" "$paths" | while IFS= read -r c; do
        [ -f "$gitattr_file" ] || touch "$gitattr_file"
        line="$c  filter=sec diff=sec"
        grep "$line" "$gitattr_file" >/dev/null ||
            echo "$line" >> "$gitattr_file"
    done
}
age_armored_header="-----BEGIN AGE ENCRYPTED FILE-----"
_is_content_encrypted() { printf "%s" "$1" | head -n1 | grep "^$age_armored_header\$" >/dev/null; }
sec_git_encrypt() {
    content=$(cat | tr -d '\0')
    file="$1"
    git_file_content=$(git show HEAD:"$file" 2>/dev/null || echo "")
    if [ -n "$git_file_content" ]; then
        ! _is_content_encrypted "$git_file_content" && printf "%s" "$content" | sec e - && return $?
        decrypted_git_file_content="$(printf "%s" "$git_file_content" | sec d -)"
        if [ "$content" = "$decrypted_git_file_content" ]; then
           printf "%s" "$git_file_content"
           return 0; fi
    fi
    printf "%s" "$content" | sec e -
}
sec_git_decrypt () {
    content=$(cat | tr -d '\0')
    [ -z "$content" ] && return 0
    printf "%s" "$content" | sec d -
}
sec_git_decrypt_from_file () {
    content=$(cat "$1")
    [ -z "$content" ] && return 0
    printf "%s" "$content" | sec d -
}

if [ "$cmd" = "on" ]; then
    turn_git_mode_off
    turn_git_mode_on

elif [ "$cmd" = "off" ]; then
    turn_git_mode_off

elif [ "$cmd" = "clean" ]; then
    sec_git_encrypt "$1"

elif [ "$cmd" = "smudge" ]; then
    sec_git_decrypt "$1"

elif [ "$cmd" = "diff" ]; then
    sec_git_decrypt_from_file "$1"

elif [ "$cmd" = "l" ] || [ "$cmd" = "ls" ] || [ "$cmd" = "list" ]; then
    if is_git_mode_on; then printf "feature: git\n\n"; fi
    sec l

elif [ -z "$cmd" ]; then
    usage
    echo
    sec help
else
    sec "$cmd" "$@"
fi


# checking git-filtered files examples
# $ git check-attr filter -- /path/to/file
# /path/to/file: filter: sec
# $ git check-attr filter -- /path/to/nonfiltered/file
# /path/to/nonfiltered/file: filter: unspecified
