#!/bin/sh

# inspiration taken from:
# https://github.com/slok/agebox
# https://github.com/biox/pa

sec_tracking_filename=.sec
age_armored_header="-----BEGIN AGE ENCRYPTED FILE-----"

usage() {
    s="$(basename $0)"
    printf %s "\
$s
    a rough handler for age-based secrets eventually stored in git

commands:
    l|list  - list tracked files and recipients

    t|track <path> [<path>] ...  - track files
    u|untrack <path> [<path>] ...  - untrack files

    e|encrypt  - encrypt all tracked files
    d|decrypt  - decrypt all tracked files

    a|add <public_key> [<public_key>] ...  - add recipients
    r|rm <public_key> [<public_key>] ...  - remove recipients

    m|modify  - edit tracking file directly with ${EDITOR:-vi}, use caution!

env vars:
    SEC_IDENTITY_FILE  - [mandatory] age/ssh identity file to use for decryption

    SEC_RECIPIENT  - [optional] your age/ssh publickey to use for enryption .
        Set this to always ensure that your pubkey is present in the recipients,
        to avoid an epic lock-out : )

    SEC_ROOT_DIR  - [optional] set the root dir forcibly, to address a bunch of use cases,
        like working with a normal directory that is not a git repo.
        If this var is unset and CWD is in a git repo, then the git repo root is used.

notes:
    sec keeps a tracking file named '$sec_tracking_filename' in the root dir .
        The file contains paths of files tracked, relative to the root dir, one per line
        and one line per recipient, starting with 'recipient: ' .
        Lines starting with '#' are considered comments and ignored .

    git dir and work tree: to work with a git dir that is, i.e. a bare repo used for dotfiles,
        just set GIT_DIR and GIT_WORK_TREE env variables
"
exit 0
}

_die() {
    printf "%s: error: %s\n" "$(basename "$0")" "$1" >&2
    exit 1
}

_warn() {
    printf "%s: warn: %s\n" "$(basename "$0")" "$1" >&2
}
_dbg() {
    [ "$SEC_DEBUG" ] &&
        printf "%s: debug: %s\n" "$(basename "$0")" "$1" >&2
}
_info() {
    printf "%s: %s\n" "$(basename "$0")" "$1" >&2
}

_rand_chars() {
    # Generate random characters by reading '/dev/urandom' with the
    # 'tr' command to translate the random bytes into a
    # configurable character set.
    #
    # The 'dd' command is then used to read only the desired length.
    #
    # Regarding usage of '/dev/urandom' instead of '/dev/random'.
    # See: https://www.2uo.de/myths-about-urandom
    #
    # $1 = number of chars to receive
    # $2 = filter for the chars
    LC_ALL=C tr -dc "$2" </dev/urandom | dd ibs=1 obs=1 count="$1" 2>/dev/null
}
_mktemp() {
    tmpdir=/dev/shm
    # Fall back to $TMPDIR or /tmp - /dev/shm is Linux-only
    # and shared memory space on other operating systems
    # have non-standard methods of setup/access.
    [ -w /dev/shm ] || tmpdir=${TMPDIR:-/tmp}
    tmpfile=$tmpdir/sec.$(_rand_chars 16 'A-Za-z0-9') ||
        _die "couldn't generate random characters"
    mkdir -p "$(dirname "$tmpfile")" ||
        _die "couldn't create temp dir"
    touch "$tmpfile" ||
        _die "couldn't create temp file"
    printf "%s" "$tmpfile"
}

_is_cwd_in_a_git_repo() {
    git rev-parse --show-toplevel >/dev/null 2>&1
    return $?
}

_get_root_dir() {
    [ -z "${SEC_ROOT_DIR:=$(git rev-parse --show-toplevel 2>/dev/null)}" ] &&
        _die "CWD is not a git repo, set SEC_ROOT_DIR explicitly or check usage"
    printf "%s" "${SEC_ROOT_DIR}"
}

_populate_recipient_file() {
    recipient_file="$1"
    # extract and populate a recipient file passed
    # if not present, add $SEC_RECIPIENT to it
    printf "" > "$recipient_file"
    cat "$sec_tracking_file_abspath" |
        grep '^recipient: ' |
        sed 's/^recipient: //' > "$recipient_file"
    [ -z "$SEC_RECIPIENT" ] && [ -z "$(cat "$recipient_file")" ] &&
        _die "no recipients added yet, check usage to add at least one"
    [ -z "$SEC_RECIPIENT" ] && return 0
    grep "^$SEC_RECIPIENT\$" "$recipient_file" >/dev/null ||
        printf "%s" "$SEC_RECIPIENT" >> "$recipient_file"
    _dbg "recipient file: $recipient_file"
    _dbg "recipient file contents: $(cat "$recipient_file")"
}

_is_file_encrypted() {
    file_to_check="$1"
    head -n1 "$file_to_check" |
        grep "^$age_armored_header\$" >/dev/null
}

sec_encrypt_file() {
    file_to_encrypt="$1"
    recipient_file="$2"
    if ! [ -f "$file_to_encrypt" ]; then
        _warn "file [$file_to_encrypt] does not exists"
        return 0; fi
    if _is_file_encrypted "$file_to_encrypt"; then
        _warn "file [$file_to_encrypt] is already encrypted"
        return 0; fi
    tmpfile=$(_mktemp)
    trap 'rm -f "$tmpfile"' EXIT
    $age -a -R "$recipient_file" -o "$tmpfile" "$file_to_encrypt" ||
        _die "cannot encrypt file [$file_to_encrypt]"
    mv -f "$tmpfile" "$file_to_encrypt"
    _dbg "encrypted file [$file_to_encrypt]"
}

sec_decrypt_file() {
    file_to_decrypt="$1"
    if ! [ -f "$file_to_decrypt" ]; then
        _warn "file [$file_to_decrypt] does not exists"
        return 0; fi
    if ! _is_file_encrypted "$file_to_decrypt"; then
        _dbg "file [$file_to_decrypt] is not encrypted"
        return 0; fi
    tmpfile=$(_mktemp)
    trap 'rm -f "$tmpfile"' EXIT
    $age -d -i "$SEC_IDENTITY_FILE" -o "$tmpfile" "$file_to_decrypt" ||
        _die "cannot decrypt file [$file_to_decrypt]"
    mv -f "$tmpfile" "$file_to_decrypt"
    _dbg "decrypted $file_to_decrypt"
}

_ensure_tracking_file_exists_and_is_decrypted() {
    [ -f "$sec_tracking_file_abspath" ] ||
        touch "$sec_tracking_file_abspath"
    sec_decrypt_file "$sec_tracking_file_abspath"
    _dbg "tracking file is decrypted"
}

sec_encrypt() {
    recipient_file=$(_mktemp)
    trap 'rm -f "$recipient_file"' EXIT
    _populate_recipient_file "$recipient_file"
    while read -r f || [ -n "$f" ]; do
        if [ -z "$f" ]; then
            _dbg "[$f] is an empty line, ignoring"
            continue
        fi
        printf "%s" "$f" | grep '^#' >/dev/null &&
            continue
        printf "%s" "$f" | grep '^recipient: ' >/dev/null &&
            continue
        _dbg "read from tracking file: $f"
        sec_encrypt_file "$sec_root_dir/$f" "$recipient_file"
    done < "$sec_tracking_file_abspath"
    sec_encrypt_file "$sec_tracking_file_abspath" "$recipient_file"
    _info "encrypted all tracked files"
}

sec_decrypt() {
    while read -r f || [ -n "$f" ]; do
        if [ -z "$f" ]; then
            _dbg "[$f] is an empty line, ignoring"
            continue
        fi
        printf "%s" "$f" | grep '^#' >/dev/null &&
            continue
        printf "%s" "$f" | grep '^recipient: ' >/dev/null &&
            continue
        _dbg "read from tracking file: $f"
        sec_decrypt_file "$sec_root_dir/$f"
    done < "$sec_tracking_file_abspath"
    _info "decrypted all tracked files"
}

_get_relative_path() {
    filepath="$1"
    _dbg "building relative path of [$filepath]"
    absolute_filepath=$(readlink -f "$filepath")
    _dbg "absolute path of [$filepath] is [$absolute_filepath]"
    printf "%s" "$absolute_filepath" | sed "s#^$sec_root_dir/##"
}

sec_track_file() {
    for ft in "$@"; do
        if [ ! -f "$ft" ]; then
            _warn "file [$ft] does not exists, not tracked"
            continue
        fi
        f=$(_get_relative_path "$ft")
        if grep "^$f\$" "$sec_tracking_file_abspath" >/dev/null; then
            _warn "file [$f] already tracked"
            continue
        fi
        echo "$f" >>"$sec_tracking_file_abspath"
        _info "tracked [$f]"
    done
}

sec_untrack_file() {
    tmpfile=$(_mktemp)
    trap 'rm -f "$tmpfile"' EXIT
    any_match="false"
    untracked_files=""
    while read -r f || [ -n "$f" ]; do
        if [ -z "$f" ]; then
            _dbg "[$f] is an empty line, ignoring"
            continue
        fi
        if printf "%s" "$f" | grep '^#' >/dev/null; then
            echo "$f" >> "$tmpfile"
            continue
        fi
        if printf "%s" "$f" | grep '^recipient: ' >/dev/null; then
            echo "$f" >> "$tmpfile"
            continue
        fi
        _dbg "check if [$f] matches files to untrack"
        match=false
        for fu in "$@"; do
            u=$(_get_relative_path "$fu")
            _dbg "try to match [$u]"
            [ "$f" = "$u" ] && match=true
        done
        if [ "$match" = "true" ]; then
            any_match="true"
            _dbg "matched [$u]"
            sec_decrypt_file "$sec_root_dir/$f"
            untracked_files="$untracked_files $f"
        else
            echo "$f" >> "$tmpfile"
        fi
    done < "$sec_tracking_file_abspath"
    if [ "$any_match" = "true" ]; then
        mv "$tmpfile" "$sec_tracking_file_abspath"
        _info "untracked files: [$untracked_files]"
    else
        _warn "files passed in input are not tracked, nothing to untrack"
    fi
}

_reencrypt_encrypted_files() {
    recipient_file=$(_mktemp)
    trap 'rm -f "$recipient_file"' EXIT
    _populate_recipient_file "$recipient_file"
    while read -r f || [ -n "$f" ]; do
        if [ -z "$f" ]; then
            _dbg "[$f] is an empty line, ignoring"
            continue
        fi
        if printf "%s" "$f" | grep '^#' >/dev/null; then
            continue
        fi
        if printf "%s" "$f" | grep '^recipient: ' >/dev/null; then
            continue
        fi
        if _is_file_encrypted "$sec_root_dir/$f"; then
            sec_decrypt_file "$sec_root_dir/$f"
            sec_encrypt_file "$sec_root_dir/$f" "$recipient_file"
        fi
    done < "$sec_tracking_file_abspath"
}

sec_add_recipients() {
    any_added="false"
    for r in "$@"; do
        if grep "recipient: $r" "$sec_tracking_file_abspath" >/dev/null; then
            _warn "recipient already present [$r]"
        else
            printf "recipient: %s" "$r" >> "$sec_tracking_file_abspath"
            any_added="true"
            _info "added recipient [$r]"
        fi
    done
    [ "$any_added" = "true" ] && _reencrypt_encrypted_files
}

sec_remove_recipients() {
    tmpfile=$(_mktemp)
    trap 'rm -f "$tmpfile"' EXIT

    removed_recipients=""
    while read -r f || [ -n "$f" ]; do
        _dbg "scanning [$f] for a recipient to remove"
        if [ -z "$f" ]; then
            _dbg "[$f] is an empty line, ignoring"
            continue
        fi
        if printf "%s" "$f" | grep '^#' >/dev/null; then
            _dbg "[$f] is a comment, ignoring"
            echo "$f" >> "$tmpfile"
            continue
        fi
        if ! printf "%s" "$f" | grep '^recipient: ' >/dev/null; then
            _dbg "[$f] is not a recipient, ignoring"
            echo "$f" >> "$tmpfile"
            continue
        fi
        _dbg "check if [$f] matches a recipient to remove"
        match="false"
        f_cleaned="$(printf "%s" "$f" | sed 's/^recipient: //')"
        for r in "$@"; do
            _dbg "try to match [$r]"
            [ "$f_cleaned" = "$r" ] &&
                match="true"
        done
        if [ "$match" = "true" ]; then
            _dbg "matched [$f]"
            removed_recipients="$removed_recipients $f_cleaned"
        else
            echo "$f" >> "$tmpfile"
        fi
    done < "$sec_tracking_file_abspath"
    if [ ! -z "$removed_recipients" ]; then
        mv -f "$tmpfile" "$sec_tracking_file_abspath"
        _info "removed recipients: [$removed_recipients ]"
        _reencrypt_encrypted_files
    else
        _warn "recipients passed in input are not present, nothing to remove"
    fi
}

sec_list_tracking() {
    if [ ! -f "$sec_tracking_file_abspath" ]; then
        _warn "no file/recipient tracked yet"
        return 0
    fi
    echo "# recipients:"
    {
        [ -z "$SEC_RECIPIENT" ] ||
        printf "%s (SEC_RECIPIENT env var)\n" "$SEC_RECIPIENT"
    cat "$sec_tracking_file_abspath" |
        grep -v '^#' | grep '^recipient: ' |
        sed 's/^recipient: //'
    } | sort
    echo; echo "# tracked files:"
    cat "$sec_tracking_file_abspath" |
        grep -v '^#' | grep -v '^recipient: ' | sort
}

sec_edit_tracking() {
    ${EDITOR:-vi} "$sec_tracking_file_abspath"
}

main() {
    : "${SEC_IDENTITY_FILE:?$(_die "setup the SEC_IDENTITY_FILE env var")}"

    age=$(command -v age || command -v rage) ||
        _die "age not found, install per https://age-encryption.org"
    # age_keygen=$(command -v age-keygen || command -v rage-keygen) ||
    #     _die "age-keygen not found, install per https://age-encryption.org"

    sec_root_dir=$(_get_root_dir)
    [ -z "$sec_root_dir" ] && exit 1
    _dbg "sec_root_dir: $sec_root_dir"
    sec_tracking_file_abspath="$sec_root_dir/$sec_tracking_filename"

    [ -d "$sec_root_dir" ] || _die "root dir [$sec_root_dir] is not a directory"

    cmd="$1"
    shift

    case $cmd in
        m*) sec_edit_tracking; return 0;;
    esac

    _ensure_tracking_file_exists_and_is_decrypted
    case $cmd in
        l*) sec_list_tracking;;
        m*) sec_edit_tracking;;
        t*) sec_track_file "$@";;
        u*) sec_untrack_file "$@";;
        e*) sec_encrypt;;
        d*) sec_decrypt;;
        a*) sec_add_recipients "$@";;
        r*) sec_remove_recipients "$@";;
        *) usage;;
    esac
}

[ "$1" ] || usage && main "$@"

# vim: set expandtab tabstop=4 shiftwidth=4:
