#!/bin/sh
s="$(basename "$0")"
usage() {
    printf "%s" "\
$s
    handles git configs to transparently use sec in your repo

    on  - activates sec in your git repo
    off  - deactivates sec from your git repo

    l  - lists infos about recipients, tracked paths, etc.

    # recipients
    a '<recipient>' [ '<recipient>'... ]  - adds recipients
    r '<recipient>' [ '<recipient>'... ]  - removes recipients

    t '<path>' [ '<path>'... ]  - tracks paths to .gitattributes (remember to quote globbings)
    u '<path>' [ '<path>'... ]  - untracks paths from .gitattributes (remember to quote globbings)

    # utilities:
    f  - try to force git to (re-)encrypt your fresh-tracked file (works only on a clean git status)

env vars:
    SEC_IDENTITY  - path to an age identity file (needed for decrypt)

files:
    <repo-root-dir>/$recipients_filename  - this file will store the recipient list for your repo
        remember to add the recipient of your identity file!
"
}
seccmd=sec
age_armored_header="-----BEGIN AGE ENCRYPTED FILE-----"
recipients_filename=".sec-recipients"
tmpdir="${TMPDIR:-/tmp}"
logfile="$tmpdir/sec-git.log"
_now() { printf "%s" "$(date '+%Y-%m-%dT%H:%M:%S')"; }
_err() { printf "%s - %s: error: %s\n" "$(_now)" "$(basename "$0")" "$1" >&2; exit 1; }
_warn() { printf "%s: warn: %s\n" "$(_now) - $(basename "$0")" "$1" >&2; }
_info() { printf "%s: %s\n" "$(_now) - $(basename "$0")" "$1" >&2; }
_dbg() { [ "$SEC_DEBUG" ] && printf "%s: debug: %s\n" "$(_now) - $(basename "$0")" "$1" >&2; return 0; }
_is_content_encrypted() { printf "%s" "$1" | head -n1 | grep "^$age_armored_header\$" >/dev/null; }
_is_git_mode_on() { git config --local filter.sec.clean >/dev/null 2>&1; }
_is_git_status_clean() { [ -z "$(git status --porcelain)" ]; }
_is_cwd_in_a_git_repo() { git rev-parse --is-inside-work-tree > /dev/null 2>&1; }
_rand_chars() { LC_ALL=C tr -dc "$2" </dev/urandom | dd ibs=1 obs=1 count="$1" 2>/dev/null; }
_mktemp() {
    tmpdir=/dev/shm
    [ -w /dev/shm ] || tmpdir=${TMPDIR:-/tmp}
    tmpfile=$tmpdir/sec.$(_rand_chars 16 'A-Za-z0-9') || _err "couldn't generate random characters"
    mkdir -p "$(dirname "$tmpfile")" || _err "couldn't create temp dir"
    touch "$tmpfile" || _err "couldn't create temp file"
    printf "%s" "$tmpfile"
}
secgit_force_git() {
    _is_git_status_clean || _err "ensure you have a clean git status to run this command"
    cd $git_root && git rm --cached -r . && git reset --hard
}
secgit_off() {
    git config --local --unset-all filter.sec.clean
    git config --local --unset-all filter.sec.smudge
    git config --local --unset-all filter.sec.required
    git config --local --unset-all diff.sec.textconv
}
secgit_on() {
    [ -f "$gitattrs_file" ] && grep 'filter=sec' "$gitattrs_file">/dev/null &&
        ( ! [ -f "$recipients_file" ] || [ -z "$(cat "$recipients_file")" ] ) &&
        _err "there are existing sec trackings in the .gitattributes file, so add some recipients first!"
    git config --local filter.sec.clean "$s clean %f"
    git config --local filter.sec.smudge "$s smudge %f"
    git config --local filter.sec.required true
    git config --local diff.sec.textconv "$s textconv"
}
secgit_clean() {
    _dbg "clean filter"
    content_tmp="$(_mktemp)"
    decrypted_content_tmp="$(_mktemp)"
    trap 'rm -f "$content_tmp" "$decrypted_content_tmp"' EXIT
    file="$1"
    _dbg "file passed: $file"
    if [ -n "$file" ]; then cat "$file" > "$content_tmp"
    else cat > "$content_tmp"; fi
    git_file_content=$(git -C "$git_root" --no-pager show HEAD:"$file" 2>/dev/null || echo "")
    _dbg "git stored content:"
    _dbg "$git_file_content"

    export SEC_RECIPIENTS="$git_root/$recipients_filename"

    # if a previous version of the file exists in git
    if [ -n "$git_file_content" ]; then
        # check if that verison was encrypted, if not, then encrypt the current version
        # it means that we just added a new path to the .gitattributes
        if ! _is_content_encrypted "$git_file_content"; then
            _dbg "git stored content was not encrypted, encrypting"
            $seccmd e < "$content_tmp"
            return $?
        fi

        _dbg "git stored content is encrypted, decrypting to check for changes"
        # else check if the new version differs from the old one
        printf "%s" "$git_file_content" | $seccmd d >"$decrypted_content_tmp"
        _dbg "decrypted git stored content:"
        _dbg "$(cat "$decrypted_content_tmp")"
        if cmp -s "$content_tmp" "$decrypted_content_tmp"; then
            _dbg "git stored content is the same as working copy content, printing git stored content"
            # if it's not changed, then output the previous encrypted content
            # we do this due to the age's non-deterministic encryption
            git -C "$git_root" --no-pager show HEAD:"$file" 2>/dev/null || echo ""
            return 0; fi
    fi
    _dbg "git stored content differs from working copy content, encrypting working copy content"
    # if the file is new, just encrypt it
    $seccmd e < "$content_tmp"
}
secgit_smudge () {
    content_tmp="$(_mktemp)"; trap 'rm -f "$content_tmp"' EXIT
    file="$1"
    if [ -n "$file" ]; then cat "$file" > "$content_tmp"
    else cat > "$content_tmp"; fi
    [ -s "$content_tmp" ] || return 0
    $seccmd d < "$content_tmp"
}
secgit_textconv () {
    content_tmp="$(_mktemp)"; trap 'rm -f "$content_tmp"' EXIT
    file="$1"
    if [ -n "$file" ]; then cat "$file" > "$content_tmp"
    else cat > "$content_tmp"; fi
    [ -s "$content_tmp" ] || return 0
    ! _is_content_encrypted <"$content_tmp" && cat "$content_tmp" && return 0
    $seccmd d < "$content_tmp"
}
secgit_track() {
    ( ! [ -f "$recipients_file" ] || [ -z "$(cat "$recipients_file")" ] ) &&
        _err "add some recipients first!"
    [ -f "$gitattrs_file" ] || touch "$gitattrs_file"
    for c in "$@"; do
        line="$c  filter=sec diff=sec -text"
        grep "$line" "$gitattrs_file" >/dev/null ||
            echo "$line" >> "$gitattrs_file"
    done; _info "paths [$*] tracked"
}
secgit_untrack() {
    ! [ -f "$gitattrs_file" ] && _warn ".gitattribute file does not exists" && return 1
    tmpfile_paths_to_remove="$(_mktemp)"; trap 'rm -f "$tmpfile_paths_to_remove"' EXIT
    for c in "$@"; do line="$c  filter=sec diff=sec -text"; echo "$line" >> "$tmpfile_paths_to_remove"; done
    new_gitattr_content="$(grep -v -F -f "$tmpfile_paths_to_remove" "$gitattrs_file")"
    if [ -z "$new_gitattr_content" ]; then rm -f "$gitattrs_file"
    else printf "%s" "$new_gitattr_content" > "$gitattrs_file"; fi
    _info "paths [$*] untracked"
}
secgit_add_recipients() {
    for r in "$@"; do
        if [ -f "$recipients_file" ] && grep "^$r\$" "$recipients_file" >/dev/null; then
            _warn "recipient already present [$r]"
        else [ -n "$(tail -c1 "$recipients_file")" ] && printf "\n" >> "$recipients_file"
            printf "%s\n" "$r" >> "$recipients_file"
            _info "added recipient [$r]"
        fi
    done
}
secgit_remove_recipients() {
    ! [ -f "$recipients_file" ] &&
        _warn "recipient file does not exists, first add some recipients" && return 0
    tmpfile_rm_recipient=$(_mktemp); trap 'rm -f "$tmpfile_rm_recipient"' EXIT
    for r in "$@"; do printf "%s\n" "$r" >> "$tmpfile_rm_recipient"; done
    new_recipient_content="$(grep -v -F -f "$tmpfile_rm_recipient" "$recipients_file")"
    if [ -z "$new_recipient_content" ]; then rm -f "$recipients_file"
    else printf "%s" "$new_recipient_content" > "$recipients_file"; fi
    _info "recipients removed"
}
secgit_list() {
    cd $git_root || _err "cannot cd to repo root"
    echo "# recipients:"
    if [ -f "$recipients_file" ]; then cat "$recipients_file" | sort | uniq
    else _warn "no recipients yet!"; fi
    echo
    echo "# trackings:"
    if [ -f "$gitattrs_file" ]; then cat "$gitattrs_file" |
        sed 's/  filter=sec diff=sec -text//' | sort | uniq
    else _warn "no trackings yet!"; fi
    echo
    echo "# tracked files:"
    tracked_files=$(git ls-files |
      xargs git check-attr filter |
      grep 'filter: sec' |
      sed 's/: filter: sec//' | sort | uniq)
    if [ ! -z "$tracked_files" ]; then echo "$tracked_files"
    else _warn "no tracked files"; fi
}
main() {
    git_root="$(git rev-parse --show-toplevel 2>/dev/null)"
    [ -z "$git_root" ] && _err "you are not in a git repo >:|"
    recipients_file="$git_root/$recipients_filename"
    gitattrs_file="$git_root/.gitattributes"
    cmd="$1"; [ -n "$cmd" ] && shift
    case $cmd in
        on) secgit_off; secgit_on && _info "activated \o/";;
        off) secgit_off && _info "deactivated :(";;
        l) secgit_list;;
        a) secgit_add_recipients "$@";;
        r) secgit_remove_recipients "$@";;
        t) secgit_track "$@";;
        u) secgit_untrack "$@";;
        f) secgit_force_git;;
        clean) secgit_clean "$@";;
        smudge) secgit_smudge;;
        textconv) secgit_textconv "$@";;
        *) usage; exit 0;;
    esac
}
[ "$1" ] || { usage; exit 0; } && main "$@"
